# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "c2OJf8iITVme1seW4nTummbr/71iFTQIxWSZlqpzQflpK6wb+WMdD5QolPPMFiVsAFt2wEEx4sxUNfeJWv4MVanCx6hbf+1IwircR+hJXL6SPnz88/O3hLZYNvSSzJwia6GAIWiSKYMxTns3jpeT0/mROv4FRkOspyJkBi454c0RmvJA9Fd6gwigeAwUhc0sMbwRaFBmlD1xBc76jolGGHe35adbtYUSmmEbPFkqJ3cI0yzju4c35u+/61Esjb8MdFKrVHcJot5g97bDva8niI/rq8R383ZtZmyl1sOieduM1Caut8NBWeMN9lRPTz/y8pkqmxWGec8FZqem/zNZLzDKe2t6Z95p7587175ICEkCaUnq4UYiUtBiWrhwaSP4OTbKWwCXsC/nV1TxTa2ph//181j3yXbzabUacsIlvg579aaN7sGj8SGSJSB1x5Z1hT974Oc0l5lgAtabZ0RPA+rD7NnOArobZlhdJaDZEo8xhBJbHVe1opr0gBQkhc7vOHK6Njl4YSGor8547yTL37X2djR5OxWX/TNKwAhE398BDCctbF2a3aK7C2espT8oqX9OUY8yOFIzBqiP7DwCDnvNb14ny77W83QZoPduP9gPoYb/ui1qfp68pZ3FN8u87IZWkghhjR2ZOvXqsdJvZhUxlJYmXpVkLaisBEK4Aw0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
