travis:
  secure:
    BINSTAR_TOKEN: oaoBbHL8ntrE6jCZlx9JDKFf0YQShvikrWr9I8MCXSBzanyoJkXI8D0bOivpQU/3sI5w951By+DQqreXQKfjiWQYrJr0tglLOz3ZWA6v2z93BkjaoCSFCfyK8L6NwU157J2s3GswTzP0+PqKRAWZTLAx7861Kz/0hJ4Z9IM1PWKB3ByXOj/nTr1x3LJ9CAEhchp+X8aGWQXR+IBf3VKKoM9IywfOENPMJ2BxYWhhqHllZlXvZhix5E+4TSk5yol89inBntjWC/l8/l1TjBi/sgOxwZhf2HK+f+PIbSrbvOMYoukeBLVXNqBO8XOha0+uCEWAmb+29gRlgZdT9qV5XO3zAmzU7yCGXf2ZMs3X2pjg+Vs5DODbEoE9tOt9npfacs8shbXki+j8WWmbLjstnFYhgJn3yAlhr9BUco2mr2+O3LG3V6KjWeBNI1JxjUZeo1SO3GgQ/7e6i3SXvkjt4O3f5Z9PmglAshzOhuQizR77NLsdfSMHCVHraD/gsgGXlKYyDmShKtq0fQ3VHeUHgd28Lzt9dTY7KzNzTdCAg4NBQuFdKtPK2blKKByHu76UmD6nNCGy0JyEFyEwna5qe7XQJtAYtNTnaXh13gBBrn8gvM8MkqdrIgLhdHz6FXIYa8ytc0XTXWr/7oKl3A4akfEQKzxzV+KM8MbSArOYrx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
