appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ld5sfMaMEXw6bUe1a+94Hzlo2R0TC7BijOM/oWhErd+9ihh0gY3VS3hX2nxDvymXJPpImscoDsCEUlpciWCJs17OVC1fAK2Iml3/fZhbrqYIgigKxIsl2UvaZtclatR/g355si4kf9RLCGkuZbq01UFfI6kPAJy7wY3NgKAbQllQjpKukkCM4hUjKjPThBj+qdfP1RkhjoiiSKkXUxZ8MhjVStWZsZSTB2zoKbS94veHFOfuR5WfRsdD7cLqy0dVkps8EznnD2g0Ok7jRQJaQ+ERNmnpyndnnBpz9FlH3JOIG2VSApQprI4e0y+88yBP3sYvJAnmF/BoSGCP7dLRY7D7V/j3AixlGu211+dAmMt41lAgqvaUkycBZ50beopeSvnzhcZKYebA3EZ5BNY7XXOtiLHQ++memMgmAp/0jj/vcoLF5mFHS0t2P8BL4uIyau0pOzucBMM113UcrUOELGR8S8NefZkZ9KMff96s/cNpR+AB5ZARR4riOUdOP5Cp0h2SC9f1/4YB5T+Rrrtko17uFOQrdi0YKLcB0o5pxI5ttdWBxSP/sLwn0Z5eWGxrcyUg/fbFSccjR9ucGjgHRkkplbbdcBICtBRWOOfFRA3KDAEobQck7362v20UP70aWR8gSZ4+T96KFRVWFPka25qeG65gg7G4OTKOn6ano54=}
